# Generated by Django 5.1.6 on 2025-02-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cybercrime_app', '0003_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='case_images/'),
        ),
        migrations.AddField(
            model_name='case',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='case_images/'),
        ),
        migrations.AddField(
            model_name='case',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='case_images/'),
        ),
        migrations.AddField(
            model_name='case',
            name='incident_place',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
