# Generated by Django 5.1.6 on 2025-02-28 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cybercrime_app', '0004_case_image1_case_image2_case_image3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='evidence_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='evidence_image1',
            field=models.ImageField(blank=True, null=True, upload_to='evidence_images/'),
        ),
        migrations.AddField(
            model_name='case',
            name='evidence_image2',
            field=models.ImageField(blank=True, null=True, upload_to='evidence_images/'),
        ),
        migrations.AddField(
            model_name='case',
            name='evidence_image3',
            field=models.ImageField(blank=True, null=True, upload_to='evidence_images/'),
        ),
        migrations.AddField(
            model_name='case',
            name='forensic_report',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='investigation_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='suspect_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='case',
            name='witness_statements',
            field=models.TextField(blank=True, null=True),
        ),
    ]
