# Generated by Django 5.1.6 on 2025-02-28 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cybercrime_app', '0005_case_evidence_description_case_evidence_image1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='investigation_notes',
        ),
    ]
