# Generated by Django 5.1.6 on 2025-02-28 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cybercrime_app', '0007_suspect'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suspect',
        ),
    ]
