# Generated by Django 5.1.6 on 2025-02-28 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cybercrime_app', '0008_delete_suspect'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='suspect_images/')),
                ('status', models.CharField(choices=[('Under Investigation', 'Under Investigation'), ('Arrested', 'Arrested'), ('Released', 'Released')], default='Under Investigation', max_length=20)),
            ],
        ),
    ]
