# Generated by Django 5.1.6 on 2025-02-28 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cybercrime_app', '0009_suspect'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='request_investigator_change',
            field=models.BooleanField(default=False),
        ),
    ]
