# Generated by Django 5.1.6 on 2025-02-28 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cybercrime_app', '0010_case_request_investigator_change'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='request_investigator_change',
        ),
        migrations.AddField(
            model_name='case',
            name='requested_investigator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_cases', to='cybercrime_app.investigator'),
        ),
    ]
