# Generated by Django 5.1.6 on 2025-02-28 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cybercrime_app', '0012_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_summary', models.TextField(blank=True, null=True)),
                ('final_conclusion', models.CharField(choices=[('Open', 'Open'), ('Solved', 'Solved'), ('Closed', 'Closed')], default='Open', max_length=50)),
                ('report_document', models.FileField(blank=True, null=True, upload_to='case_reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cybercrime_app.case')),
                ('identified_suspect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cybercrime_app.suspect')),
                ('investigator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cybercrime_app.investigator')),
            ],
        ),
    ]
