# Generated by Django 5.1.6 on 2025-02-28 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cybercrime_app', '0013_caseanalysis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caseanalysis',
            name='report_document',
        ),
    ]
