# Generated by Django 5.1.6 on 2025-02-28 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cybercrime_app', '0015_alter_investigator_investigator_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigator',
            name='investigator_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
