# Generated by Django 4.2.3 on 2025-10-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cybercrime_app', '0016_alter_investigator_investigator_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='evidence_video',
            field=models.FileField(blank=True, null=True, upload_to='evidence_videos/'),
        ),
        migrations.AddField(
            model_name='case',
            name='video_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='video_verdict',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
