# Generated by Django 4.2.3 on 2025-10-28 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cybercrime_app', '0017_case_evidence_video_case_video_confidence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Court1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_name', models.CharField(max_length=100)),
                ('court_type', models.CharField(max_length=100)),
                ('judge_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('address', models.TextField()),
                ('court_image', models.ImageField(blank=True, null=True, upload_to='court_images/')),
                ('court_idd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
