# Generated by Django 4.2.3 on 2025-10-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cybercrime_app', '0018_court1'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='victim_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
