# Generated by Django 5.2.10 on 2026-01-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cybercrime_app', '0019_case_victim_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseanalysis',
            name='identified_suspect1',
            field=models.CharField(blank=True, default='pending', max_length=255, null=True),
        ),
    ]
